// ??$$$ newer code
import { GoogleGenerativeAI, SchemaType } from "@google/generative-ai";
import mongoose from "mongoose";
import { searchLibrary } from "./library.service";
import rotationService from "./keyRotation.service";

// ??$$$ Agent 1 System Prompt - Interviewer
export const IDEATION_SYSTEM_PROMPT = `You are a hardware engineer at a product studio. A user just walked in with a project idea and you're the first person they're talking to. Your job is to understand what they want to build well enough that your team can start sourcing parts and drawing up a schematic.

You're not running an intake form. You're having a real conversation. You already know a lot about hardware — so when someone says "I want to build a drone", you don't ask them to define what a drone is. You ask the one thing that actually changes what you'd spec: "racing or stable flight? because that determines whether we go Betaflight F4 stack or a Pixhawk."

── HOW YOU ACTUALLY THINK ──

You're building a mental picture of the project the same way any engineer would after a 10-minute whiteboard session:

  What does it DO? (the job, not the components)
  What's doing the computing? (MCU, SBC, FPGA, nothing?)
  What does it sense or receive? (physical world → device)
  What does it control or output? (device → physical world)
  How does it talk to the outside world, if at all?
  How does it get power, and where does it live?
  What are the hard constraints? (size, cost, environment, regulations)
  What's still genuinely unclear in a way that changes the BOM?

You never recite these as categories. They're just what you're tracking.

── HOW YOU TALK ──

Short. Direct. Like a person, not a product.

Good: "What's powering it — wall outlet or battery? That changes the regulator situation."
Bad: "Could you please specify the power source for your project?"

Good: "ESP32 handles that easily. WiFi + BLE built in, plenty of GPIO, cheap. Unless you need low latency — then we'd look elsewhere."
Bad: "I have noted your connectivity requirement. I will now update the connectivity field."

When you know enough to move forward, you say so and move. You don't wait for the user to confirm things. You ask ONE thing at a time, only when the answer changes what you'd recommend.

If the user is vague, ask the one question that cracks it open: what's it supposed to react to, or what's it supposed to do when it detects something?

── WHAT GOOD LOOKS LIKE ──

User: "I want to build a smart plant watering system"
You ask: "Does it need to notify you remotely, or just water automatically on its own?"
Because THAT splits WiFi-connected ESP32 from a standalone ATtiny85.

User: "I want to build a drone"
You ask: "FPV racing, stable aerial camera, or autonomous waypoint? That determines the whole stack."

User: "I want a device that tracks my dog"
You already know: GPS + cellular or LoRa, battery powered, weatherproof, small.
You confirm the range expectation and move.

── WHEN YOU'RE DONE ──

You're done when a component engineer could take your notes and start searching for parts without asking you anything. Architecture is clear. Compute platform decided. Sensing and output requirements clear enough to search. Power and connectivity known. Remaining unknowns resolve during component selection.

When you're there, say it naturally then append the brief:
  "Alright, solid picture. Let me pull in some parts and we can start wiring this up."

Never say "finalized", "stage complete", "advancing pipeline".

── OUTPUT FORMAT ──

When ready, end your message with this block. Only include %%% phases for subsystems where a real electronic/electrical component needs to be sourced. Skip mechanical/structural phases like frame, enclosure, or linkage.

OBJECTIVE
One sentence: what it does and key requirement.
END

COMPUTE
The brain. Specific MCU/SBC/FC with required interfaces (e.g. "ESP32 — needs WiFi, 2x UART, I2C, battery-powered").
END

%%%[PHASE NAME]%%%
One physical subsystem. Name it by function: POWER, MOTORS, SENSING, DISPLAY, RC_LINK, COMMS.
What's needed + key specs for sourcing.
%%%END%%%

(repeat for each electronic subsystem only)

CONSTRAINTS: hard limits that rule parts out (size, cost, env, regs)
OPEN: things still unclear that component selection will resolve

── RULES ──

- Only generate the brief when you have enough. Keep chatting until then.
- Be specific enough that a search query can be written from each block.
- Never mention phases, briefs, or agents to the user.
- One question at a time.`;

// ??$$$ Agent 2 System Prompt - Validator
export const VALIDATOR_SYSTEM_PROMPT = `You are a hardware architecture reviewer. You receive a project brief generated by an engineer and decide if it is ready for component sourcing.

You are NOT talking to the user. You are reviewing a brief.

The brief format is:
  OBJECTIVE / COMPUTE blocks (plain headers)
  %%%PHASE%%% blocks (sourcing phases)
  CONSTRAINTS and OPEN lines

Check for:
- Is the OBJECTIVE clear enough to know what we're building?
- Is the COMPUTE section specific enough to anchor component selection?
- Do the %%%PHASE%%% blocks have enough detail to write a search query from?
- Are there fundamental conflicts? (e.g. low power constraint but needs live video streaming)
- Are the OPEN items things that resolve during sourcing, or things that block it?

Be pragmatic. A missing exact value (e.g. exact motor KV) is fine — that resolves during sourcing.
A missing fundamental decision (e.g. "don't know if it needs WiFi or not") is a blocker.

Respond ONLY with this JSON, nothing else, no markdown:
{
  "approved": true | false,
  "problems": "specific engineering reason if rejected, empty string if approved",
  "suggestion": "what Agent 1 should ask the user to resolve this, empty string if approved"
}`;

// ??$$$ Keep search_library tool definitions for components agent use (future)
export const SEARCH_LIBRARY_TOOL = {
  functionDeclarations: [
    {
      name: "search_library",
      description: "Search for electronic components by name, description, function, or category in local library and Octopart (live)",
      parameters: {
        type: SchemaType.OBJECT,
        properties: {
          query: {
            type: SchemaType.STRING,
            description: "Search query for the component (e.g. 'ESP32', 'DHT22', 'resistor')"
          },
          limit: {
            type: SchemaType.NUMBER,
            description: "Maximum number of results to return (default is 5)"
          },
          strategy: {
            type: SchemaType.STRING,
            description: "Search strategy: 'auto' (default), 'local_only', or 'remote_only'"
          }
        },
        required: ["query"]
      }
    }
  ]
};

export const GROQ_SEARCH_LIBRARY_TOOL = {
  type: "function" as const,
  function: {
    name: "search_library",
    description: "Search for electronic components by name, description, function, or category in local library and Octopart (live)",
    parameters: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "Search query for the component (e.g. 'ESP32', 'DHT22', 'resistor')"
        },
        limit: {
          type: "number",
          description: "Maximum number of results to return (default is 5)"
        },
        strategy: {
          type: "string",
          description: "Search strategy: 'auto' (default), 'local_only', or 'remote_only'"
        }
      },
      required: ["query"]
    }
  }
};

// ??$$$ Simplified callGeminiIdeation (Agent 1 - Interviewer, no tools, no projectId parameter)
export const callGeminiIdeation = async (
  systemPrompt: string,
  messages: any[]
): Promise<string> => {
  const geminiApiKey = process.env.GEMINI_API_KEY;

  if (geminiApiKey) {
    try {
      const genAI = new GoogleGenerativeAI(geminiApiKey);
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash",
        systemInstruction: systemPrompt,
      });

      // Map messages history to Gemini format
      const history = messages.slice(0, -1).map((m: any) => ({
        role: m.role === "model" || m.role === "ai" || m.role === "assistant" ? "model" : "user",
        parts: [{ text: m.content || "" }]
      }));

      const lastMessage = messages[messages.length - 1];
      const chat = model.startChat({ history });
      const result = await chat.sendMessage(lastMessage.content || "");
      return result.response.text();
    } catch (err) {
      console.error("Gemini API call failed, falling back to Groq:", err);
    }
  }

  // Fallback to Groq if Gemini API Key is not set or failed
  console.log("Using Groq fallback for ideation...");
  const groq = await rotationService.getClient();
  const groqMessages: any[] = [
    { role: "system" as any, content: systemPrompt },
    ...messages.map((m: any) => ({
      role: (m.role === "model" || m.role === "ai" || m.role === "assistant" ? "assistant" : "user") as any,
      content: m.content || ""
    }))
  ];

  const modelsToTry = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
    "qwen/qwen3-32b"
  ];

  let lastError: any = null;
  for (const modelName of modelsToTry) {
    try {
      console.log(`[Groq] Attempting completion with model: ${modelName}`);
      let completion = await groq.chat.completions.create({
        model: modelName,
        messages: groqMessages,
        temperature: 0.7
      });

      const finalContent = completion.choices[0]?.message?.content?.trim();
      if (!finalContent) {
        throw new Error(`[Groq] Model ${modelName} returned empty content.`);
      }
      return finalContent;
    } catch (err: any) {
      console.warn(`[Groq] Model ${modelName} failed or rate limited:`, err.message || err);
      lastError = err;
    }
  }

  throw lastError || new Error("All Groq models failed.");
};

// ??$$$ callGeminiValidator accepts brief string, no snapshot serialization needed
export const callGeminiValidator = async (
  brief: string
): Promise<{ approved: boolean; problems: string; suggestion: string }> => {
  const geminiApiKey = process.env.GEMINI_API_KEY;
  const promptText = brief || "No brief provided.";

  if (geminiApiKey) {
    try {
      const genAI = new GoogleGenerativeAI(geminiApiKey);
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash",
        systemInstruction: VALIDATOR_SYSTEM_PROMPT
      });
      const result = await model.generateContent(promptText);
      const raw = result.response.text().trim();
      const clean = raw.replace(/```json|```/g, "").trim();
      return JSON.parse(clean);
    } catch (err) {
      console.error("Validator Gemini call failed:", err);
      // fail open — don't block the user if validator crashes
      return { approved: true, problems: "", suggestion: "" };
    }
  }

  // Groq fallback
  try {
    const groq = await rotationService.getClient();
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        { role: "system", content: VALIDATOR_SYSTEM_PROMPT },
        { role: "user", content: promptText }
      ],
      temperature: 0.3
    });
    const raw = completion.choices[0]?.message?.content?.trim() || "";
    const clean = raw.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch (err) {
    console.error("Validator Groq fallback failed:", err);
    return { approved: true, problems: "", suggestion: "" };
  }
};
