// ??$$$ group 2 - Ideation Stage (Phase 1)
// ??$$$ newer code
import { GoogleGenerativeAI, SchemaType } from "@google/generative-ai";
import mongoose from "mongoose";
import { searchLibrary } from "./library.service";
import rotationService from "./keyRotation.service";

// ??$$$ Agent 1 System Prompt - Interviewer
export const IDEATION_SYSTEM_PROMPT = `You are a hardware engineer at a product studio. A user just walked in with a project idea and you're the first person they're talking to. Your job is to understand what they want to build well enough that your team can start sourcing parts and drawing up a schematic.

You're not running an intake form. You're having a real conversation. You already know a lot about hardware — so when someone says "I want to build a drone", you don't ask them to define what a drone is. You ask the one thing that actually changes what you'd spec: "racing or stable flight? because that determines whether we go Betaflight F4 stack or a Pixhawk."

── HOW YOU ACTUALLY THINK ──

You're building a mental picture of the project the same way any engineer would after a 10-minute whiteboard session:

  What does it DO? (the job, not the components)
  What's doing the computing? (MCU, SBC, FPGA, nothing?)
  What does it sense or receive? (physical world → device)
  What does it control or output? (device → physical world)
  How does it talk to the outside world, if at all?
  How does it get power, and where does it live?
  What are the hard constraints? (size, cost, environment, regulations)
  What's still genuinely unclear in a way that changes the BOM?

You never recite these as categories. They're just what you're tracking.

── HOW YOU TALK ──

Short. Direct. Like a person, not a product.

Good: "What's powering it — wall outlet or battery? That changes the regulator situation."
Bad: "Could you please specify the power source for your project?"

Good: "ESP32 handles that easily. WiFi + BLE built in, plenty of GPIO, cheap. Unless you need low latency — then we'd look elsewhere."
Bad: "I have noted your connectivity requirement. I will now update the connectivity field."

When you know enough to move forward, you say so and move. You don't wait for the user to confirm things. You ask ONE thing at a time, only when the answer changes what you'd recommend.

If the user is vague, ask the one question that cracks it open: what's it supposed to react to, or what's it supposed to do when it detects something?

── WHAT GOOD LOOKS LIKE ──

User: "I want to build a smart plant watering system"
You ask: "Does it need to notify you remotely, or just water automatically on its own?"
Because THAT splits WiFi-connected ESP32 from a standalone ATtiny85.

User: "I want to build a drone"
You ask: "FPV racing, stable aerial camera, or autonomous waypoint? That determines the whole stack."

User: "I want a device that tracks my dog"
You already know: GPS + cellular or LoRa, battery powered, weatherproof, small.
You confirm the range expectation and move.

── WHEN YOU'RE DONE ──

You're done when a component engineer could take your notes and start searching for parts without asking you anything. Architecture is clear. Compute platform decided. Sensing and output requirements clear enough to search. Power and connectivity known. Remaining unknowns resolve during component selection.

When you're there, say it naturally then append the brief:
  "Alright, solid picture. Let me pull in some parts and we can start wiring this up."

Never say "finalized", "stage complete", "advancing pipeline".

── OUTPUT FORMAT ──

When ready, end your message with this block. Only include %%% phases for subsystems where a real electronic/electrical component needs to be sourced. Skip mechanical/structural phases like frame, enclosure, or linkage.

OBJECTIVE
One sentence: what it does and key requirement.
END

COMPUTE
The brain. Specific MCU/SBC/FC with required interfaces (e.g. "ESP32 — needs WiFi, 2x UART, I2C, battery-powered").
END

%%%[PHASE NAME]%%%
One physical subsystem. Name it by function: POWER, MOTORS, SENSING, DISPLAY, RC_LINK, COMMS.
What's needed + key specs for sourcing.
%%%END%%%

(repeat for each electronic subsystem only)

CONSTRAINTS: hard limits that rule parts out (size, cost, env, regs)
OPEN: things still unclear that component selection will resolve

── RULES ──

- Only generate the brief when you have enough. Keep chatting until then.
- Be specific enough that a search query can be written from each block.
- Never mention phases, briefs, or agents to the user.
- One question at a time.`;

// ??$$$ Agent 2 System Prompt - Validator
export const VALIDATOR_SYSTEM_PROMPT = `You are a hardware architecture reviewer. You receive a project brief generated by an engineer and decide if it is ready for component sourcing.

You are NOT talking to the user. You are reviewing a brief.

The brief format is:
  OBJECTIVE / COMPUTE blocks (plain headers)
  %%%PHASE%%% blocks (sourcing phases)
  CONSTRAINTS and OPEN lines

Check for:
- Is the OBJECTIVE clear enough to know what we're building?
- Is the COMPUTE section specific enough to anchor component selection?
- Do the %%%PHASE%%% blocks have enough detail to write a search query from?
- Are there fundamental conflicts? (e.g. low power constraint but needs live video streaming)
- Are the OPEN items things that resolve during sourcing, or things that block it?

Be pragmatic. A missing exact value (e.g. exact motor KV) is fine — that resolves during sourcing.
A missing fundamental decision (e.g. "don't know if it needs WiFi or not") is a blocker.

Respond ONLY with this JSON, nothing else, no markdown:
{
  "approved": true | false,
  "problems": "specific engineering reason if rejected, empty string if approved",
  "suggestion": "what Agent 1 should ask the user to resolve this, empty string if approved"
}`;

// ??$$$ Keep search_library tool definitions for components agent use (future)
export const SEARCH_LIBRARY_TOOL = {
  functionDeclarations: [
    {
      name: "search_library",
      description: "Search for electronic components by name, description, function, or category in local library and Octopart (live)",
      parameters: {
        type: SchemaType.OBJECT,
        properties: {
          query: {
            type: SchemaType.STRING,
            description: "Search query for the component (e.g. 'ESP32', 'DHT22', 'resistor')"
          },
          limit: {
            type: SchemaType.NUMBER,
            description: "Maximum number of results to return (default is 5)"
          },
          strategy: {
            type: SchemaType.STRING,
            description: "Search strategy: 'auto' (default), 'local_only', or 'remote_only'"
          }
        },
        required: ["query"]
      }
    }
  ]
};

export const GROQ_SEARCH_LIBRARY_TOOL = {
  type: "function" as const,
  function: {
    name: "search_library",
    description: "Search for electronic components by name, description, function, or category in local library and Octopart (live)",
    parameters: {
      type: "object",
      properties: {
        query: {
          type: "string",
          description: "Search query for the component (e.g. 'ESP32', 'DHT22', 'resistor')"
        },
        limit: {
          type: "number",
          description: "Maximum number of results to return (default is 5)"
        },
        strategy: {
          type: "string",
          description: "Search strategy: 'auto' (default), 'local_only', or 'remote_only'"
        }
      },
      required: ["query"]
    }
  }
};

// ??$$$ Simplified callGeminiIdeation (Agent 1 - Interviewer, no tools, no projectId parameter)
/*
export const callGeminiIdeation = async (
  systemPrompt: string,
  messages: any[]
): Promise<string> => {
  const geminiApiKey = process.env.GEMINI_API_KEY;

  if (geminiApiKey) {
    try {
      const genAI = new GoogleGenerativeAI(geminiApiKey);
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash",
        systemInstruction: systemPrompt,
      });

      // Map messages history to Gemini format
      const history = messages.slice(0, -1).map((m: any) => ({
        role: m.role === "model" || m.role === "ai" || m.role === "assistant" ? "model" : "user",
        parts: [{ text: m.content || "" }]
      }));

      const lastMessage = messages[messages.length - 1];
      const chat = model.startChat({ history });
      const result = await chat.sendMessage(lastMessage.content || "");
      return result.response.text();
    } catch (err) {
      console.error("Gemini API call failed, falling back to Groq:", err);
    }
  }

  // Fallback to Groq if Gemini API Key is not set or failed
  console.log("Using Groq fallback for ideation...");
  const groq = await rotationService.getClient();
  const groqMessages: any[] = [
    { role: "system" as any, content: systemPrompt },
    ...messages.map((m: any) => ({
      role: (m.role === "model" || m.role === "ai" || m.role === "assistant" ? "assistant" : "user") as any,
      content: m.content || ""
    }))
  ];

  const modelsToTry = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant",
    "qwen/qwen3-32b"
  ];

  let lastError: any = null;
  for (const modelName of modelsToTry) {
    try {
      console.log(`[Groq] Attempting completion with model: ${modelName}`);
      let completion = await groq.chat.completions.create({
        model: modelName,
        messages: groqMessages,
        temperature: 0.7
      });

      const finalContent = completion.choices[0]?.message?.content?.trim();
      if (!finalContent) {
        throw new Error(`[Groq] Model ${modelName} returned empty content.`);
      }
      return finalContent;
    } catch (err: any) {
      console.warn(`[Groq] Model ${modelName} failed or rate limited:`, err.message || err);
      lastError = err;
    }
  }

  throw lastError || new Error("All Groq models failed.");
};
*/
// ??$$$ newer code - Use Groq llama-scout instead of Gemini
export const callGeminiIdeation = async (
  systemPrompt: string,
  messages: any[]
): Promise<string> => {
  try {
    const groq = await rotationService.getClient();
    const groqMessages: any[] = [
      { role: "system", content: systemPrompt },
      ...messages.map((m: any) => ({
        role: m.role === "model" || m.role === "ai" || m.role === "assistant" ? "assistant" : "user",
        content: m.content || ""
      }))
    ];
    console.log(`[Groq] Call ideation using qwen/qwen3-32b`);
    const completion = await groq.chat.completions.create({
      model: "qwen/qwen3-32b",
      messages: groqMessages,
      temperature: 0.7
    });
    return completion.choices[0]?.message?.content?.trim() || "";
  } catch (err: any) {
    console.error("Groq llama-scout ideation failed, trying fallback:", err);
    if (err?.status === 429) {
      await rotationService.handleRateLimit();
    }
  }

  // Fallback models if llama-scout fails
  const groq = await rotationService.getClient();
  const groqMessages: any[] = [
    { role: "system", content: systemPrompt },
    ...messages.map((m: any) => ({
      role: m.role === "model" || m.role === "ai" || m.role === "assistant" ? "assistant" : "user",
      content: m.content || ""
    }))
  ];
  const modelsToTry = [
    "llama-3.3-70b-versatile",
    "llama-3.1-8b-instant"
  ];
  let lastError: any = null;
  for (const modelName of modelsToTry) {
    try {
      console.log(`[Groq Fallback] Attempting completion with model: ${modelName}`);
      let completion = await groq.chat.completions.create({
        model: modelName,
        messages: groqMessages,
        temperature: 0.7
      });
      return completion.choices[0]?.message?.content?.trim() || "";
    } catch (err: any) {
      console.warn(`[Groq Fallback] Model ${modelName} failed:`, err.message || err);
      if (err?.status === 429) {
        await rotationService.handleRateLimit();
      }
      lastError = err;
    }
  }
  throw lastError || new Error("All Groq models failed.");
};

// ??$$$ callGeminiValidator accepts brief string, no snapshot serialization needed
/*
export const callGeminiValidator = async (
  brief: string
): Promise<{ approved: boolean; problems: string; suggestion: string }> => {
  const geminiApiKey = process.env.GEMINI_API_KEY;
  const promptText = brief || "No brief provided.";

  if (geminiApiKey) {
    try {
      const genAI = new GoogleGenerativeAI(geminiApiKey);
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash",
        systemInstruction: VALIDATOR_SYSTEM_PROMPT
      });
      const result = await model.generateContent(promptText);
      const raw = result.response.text().trim();
      const clean = raw.replace(/```json|```/g, "").trim();
      return JSON.parse(clean);
    } catch (err) {
      console.error("Validator Gemini call failed:", err);
      // fail open — don't block the user if validator crashes
      return { approved: true, problems: "", suggestion: "" };
    }
  }

  // Groq fallback
  try {
    const groq = await rotationService.getClient();
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        { role: "system", content: VALIDATOR_SYSTEM_PROMPT },
        { role: "user", content: promptText }
      ],
      temperature: 0.3
    });
    const raw = completion.choices[0]?.message?.content?.trim() || "";
    const clean = raw.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch (err) {
    console.error("Validator Groq fallback failed:", err);
    return { approved: true, problems: "", suggestion: "" };
  }
};
*/
// ??$$$ newer code - Use Groq llama-scout instead of Gemini for Validator
export const callGeminiValidator = async (
  brief: string
): Promise<{ approved: boolean; problems: string; suggestion: string }> => {
  const promptText = brief || "No brief provided.";
  try {
    const groq = await rotationService.getClient();
    console.log(`[Groq] Call validator using qwen/qwen3-32b`);
    const completion = await groq.chat.completions.create({
      model: "qwen/qwen3-32b",
      messages: [
        { role: "system", content: VALIDATOR_SYSTEM_PROMPT },
        { role: "user", content: promptText }
      ],
      temperature: 0.3
    });
    const raw = completion.choices[0]?.message?.content?.trim() || "";
    const clean = raw.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch (err: any) {
    console.error("Groq llama-scout validator failed, trying fallback:", err);
    if (err?.status === 429) {
      await rotationService.handleRateLimit();
    }
  }

  // Fallback to standard Groq completion
  try {
    const groq = await rotationService.getClient();
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        { role: "system", content: VALIDATOR_SYSTEM_PROMPT },
        { role: "user", content: promptText }
      ],
      temperature: 0.3
    });
    const raw = completion.choices[0]?.message?.content?.trim() || "";
    const clean = raw.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch (err) {
    console.error("Validator fallback failed:", err);
    return { approved: true, problems: "", suggestion: "" };
  }
};

// ??$$$
// ??$$$ newer code
export const MILESTONE_GENERATOR_PROMPT = `You are a curriculum design agent.
Your job is to generate milestone builds for a MERN stack hardware project builder.
Analyze the project objective, compute core, BOM list, ideation phases, and the user's skillLevel.
The user's skillLevel will be one of: "beginner", "intermediate", "experienced".

Break down the project's build phase into sequential or parallel milestones. Each milestone must test a specific subsystem before complete integration.

Rules:
1. The first milestone (order === 1) MUST have status "ready" and all others MUST have status "locked".
2. Milestone 1 MUST always be a bare LED blink with zero external dependencies. No libraries. No sensors. No WiFi. Just pinMode and digitalWrite. This verifies the MCU is programmable and running before anything else.
3. Each milestone must have fields:
   - "id": a unique string (e.g. "milestone_1", "milestone_2")
   - "order": number starting from 1
   - "title": a concise title
   - "objective": what this milestone builds/tests
   - "componentsInvolved": array of keys from the BOM
   - "wiringInstructions": clear step-by-step wiring instructions. For beginners: be very step-by-step and explanatory. For experienced users: be compact and point out pin numbers and voltage specifications directly.
   - "code": the C++/Arduino sketch or MicroPython code required to run this subsystem. Make sure it compiles, fits the MCU, and includes appropriate comments based on skill level.
   - "explanation": a concise educational explanation. Adjust details based on skillLevel.
   - "test": an object containing:
     - "expectedSerialOutput": expected string printed to Serial monitor (or described output)
     - "passCondition": what indicates a pass (e.g. "Distance prints correctly every second")
     - "commonProblems": array of strings listing common troubleshooting steps
   - "simulatable": boolean. Set to false when the milestone involves physical-only actions (motor spin, RC pairing, sensor physical placement, soldering) that cannot be represented in Wokwi simulation. Set to true for all MCU code + sensor reading milestones that have Wokwi equivalents.
   - "dependsOn": array of milestone IDs that must be completed before this milestone can be started. E.g. milestone_2 depends on ["milestone_1"].
   - "debugMessages": empty array []
   - "requiredLibraries": array of objects declaring libraries for every #include used in the code. Group them as follows:
     - "name": string. Exact Arduino Library Manager name, or header filename for core libraries (e.g. "WiFi", "Wire", "SPI", "PulsePosition", "BasicLinearAlgebra").
     - "version": optional string (e.g. "1.0.0", "3.2.0")
     - "type": "core" | "library_manager" | "manual"
       - "core": comes built-in with the board core, no install needed (e.g., WiFi.h on esp32, SPI.h, Wire.h).
       - "library_manager": available in the standard library manager registry (e.g., Adafruit MPU6050, PulsePosition, BasicLinearAlgebra).
       - "manual": custom library, must be installed manually (provide details).
     - "installCommand": string. Only required for "manual" type libraries or special commands.

Respond ONLY with a JSON array containing the list of milestones, nothing else. No markdown, no triple backticks.`;

// ??$$$
export const DEBUG_COACH_PROMPT = `You are a hardware debugging coach.
A user is stuck on a build milestone. You have:
1. Milestone title and objective.
2. The code they compiled.
3. The expected serial output pattern.
4. The actual error or problem description they wrote.
5. The actual serial output they entered.

Review the information and previous message logs. Provide concise, friendly, and highly specific engineering advice to fix the issue. Focus on pin connections, logic errors, missing pull-ups, or bad baud rates. Keep it educational but direct.`;

// ??$$$
export const MILESTONE_REGENERATE_PROMPT = `You are a hardware firmware code generator.
Regenerate the code for a specific milestone build task.
Make sure it compiles and fits the objective.
Respond with ONLY the raw code, without markdown, without backticks (do not wrap in \`\`\`cpp).`;

// ??$$$
export const COMPONENT_ISSUE_SYSTEM_PROMPT = `You are a hardware engineering advisor.
A user has run into a physical component issue during a build milestone.
Review the milestone context, the target component key, and the user's reported problem.
Advise them on:
1. How they can work around it locally, or
2. If they should swap the component for a better alternative.

Respond with ONLY a JSON object:
{
  "recommendSwap": true | false,
  "alternativeComponent": "suggested component key or name, or empty string",
  "explanation": "clear engineering explanation of why they can work around it or why they must swap"
}`;

// ??$$$
export const SERIAL_VALIDATION_SYSTEM_PROMPT = `You are an automated hardware test grader.
Compare the actual serial logs observed by the user against the expected serial output pattern and pass conditions.
Determine if it is a successful pass.

Respond with ONLY a JSON object:
{
  "pass": true | false,
  "confidence": "high" | "medium" | "low",
  "analysis": "detailed explanation of why the output matches or fails validation",
  "suggestion": "actionable troubleshooting step if failed, or null if passed"
}`;

// ??$$$
/*
export const callAI = async (systemInstruction: string, promptText: string): Promise<string> => {
  const geminiApiKey = process.env.GEMINI_API_KEY;
  if (geminiApiKey) {
    try {
      const genAI = new GoogleGenerativeAI(geminiApiKey);
      const model = genAI.getGenerativeModel({
        model: "gemini-2.5-flash",
        systemInstruction
      });
      const result = await model.generateContent(promptText);
      return result.response.text().trim();
    } catch (err) {
      console.error("Gemini callAI failed, falling back to Groq:", err);
    }
  }

  // Groq fallback
  try {
    const groq = await rotationService.getClient();
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        { role: "system", content: systemInstruction },
        { role: "user", content: promptText }
      ],
      temperature: 0.3
    });
    return completion.choices[0]?.message?.content?.trim() || "";
  } catch (err) {
    console.error("Groq fallback callAI failed:", err);
    throw err;
  }
};
*/
// ??$$$ newer code - Use Groq llama-scout instead of Gemini for callAI
export const callAI = async (systemInstruction: string, promptText: string): Promise<string> => {
  try {
    const groq = await rotationService.getClient();
    console.log(`[Groq] callAI using qwen/qwen3-32b`);
    const completion = await groq.chat.completions.create({
      model: "qwen/qwen3-32b",
      messages: [
        { role: "system", content: systemInstruction },
        { role: "user", content: promptText }
      ],
      temperature: 0.3
    });
    return completion.choices[0]?.message?.content?.trim() || "";
  } catch (err: any) {
    console.error("Groq llama-scout callAI failed, trying fallback:", err);
    if (err?.status === 429) {
      await rotationService.handleRateLimit();
    }
  }

  // Fallback to standard Groq completion
  try {
    const groq = await rotationService.getClient();
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: [
        { role: "system", content: systemInstruction },
        { role: "user", content: promptText }
      ],
      temperature: 0.3
    });
    return completion.choices[0]?.message?.content?.trim() || "";
  } catch (err) {
    console.error("Groq fallback callAI failed:", err);
    throw err;
  }
};

// ??$$$
export const callGeminiMilestoneGenerator = async (
  brief: string,
  objective: string,
  compute: string,
  phases: Record<string, string>,
  bom: any[],
  constraints: string,
  skillLevel: string
): Promise<any[]> => {
  const userPrompt = `Project Brief Details:
Objective: ${objective}
Compute Brain: ${compute}
System Brief: ${brief}
Constraints: ${constraints}
Phases: ${JSON.stringify(phases, null, 2)}
Bill of Materials (BOM): ${JSON.stringify(bom.map(b => ({ key: b.key, displayName: b.displayName, qty: b.qty, purpose: b.purpose })), null, 2)}
User Skill Level: ${skillLevel}

Generate the milestones array.`;

  try {
    const raw = await callAI(MILESTONE_GENERATOR_PROMPT, userPrompt);
    const clean = raw.replace(/```json|```/g, "").trim();
    const parsed = JSON.parse(clean);
    if (Array.isArray(parsed)) {
      if (parsed.length > 0) {
        parsed.forEach((m, idx) => {
          m.status = idx === 0 ? "ready" : "locked";
        });
      }
      return parsed;
    }
  } catch (err) {
    console.error("Milestone generation parsing failed:", err);
  }
  return [];
};

// ??$$$
export const callGeminiDebugCoachIterative = async (
  milestone: any,
  debugMessages: any[]
): Promise<string> => {
  const systemInstruction = `${DEBUG_COACH_PROMPT}

Milestone context:
Title: ${milestone.title}
Objective: ${milestone.objective}
Expected Output: ${milestone.test?.expectedSerialOutput}
Code:
\`\`\`cpp
${milestone.code}
\`\`\``;

  // ??$$$ newer code - Use Groq llama-scout instead of Gemini for Debug Coach
  /*
    const geminiApiKey = process.env.GEMINI_API_KEY;
    if (geminiApiKey && debugMessages.length > 0) {
      try {
        const genAI = new GoogleGenerativeAI(geminiApiKey);
        const model = genAI.getGenerativeModel({
          model: "gemini-2.5-flash",
          systemInstruction
        });
        const history = debugMessages.slice(0, -1).map((m: any) => ({
          role: m.role === "model" ? "model" : "user",
          parts: [{ text: m.content || "" }]
        }));
        const lastMessage = debugMessages[debugMessages.length - 1];
        const chat = model.startChat({ history });
        const result = await chat.sendMessage(lastMessage.content || "");
        return result.response.text().trim();
      } catch (err) {
        console.error("Gemini iterative debug coach failed, trying Groq fallback:", err);
      }
    }
  
    // Groq fallback
    try {
      const groq = await rotationService.getClient();
      const groqMessages = [
        { role: "system", content: systemInstruction },
        ...debugMessages.map((m: any) => ({
          role: m.role === "model" ? "assistant" : "user",
          content: m.content || ""
        }))
      ];
      const completion = await groq.chat.completions.create({
        model: "llama-3.3-70b-versatile",
        messages: groqMessages as any,
        temperature: 0.5
      });
      return completion.choices[0]?.message?.content?.trim() || "";
    } catch (err) {
      console.error("Groq iterative debug coach failed:", err);
      return "Failed to get debugging advice. Check pins and try again.";
    }
  };
  */
  try {
    const groq = await rotationService.getClient();
    const groqMessages = [
      { role: "system", content: systemInstruction },
      ...debugMessages.map((m: any) => ({
        role: m.role === "model" ? "assistant" : "user",
        content: m.content || ""
      }))
    ];
    console.log(`[Groq] Debug Coach using qwen/qwen3-32b`);
    const completion = await groq.chat.completions.create({
      model: "qwen/qwen3-32b",
      messages: groqMessages as any,
      temperature: 0.5
    });
    return completion.choices[0]?.message?.content?.trim() || "";
  } catch (err: any) {
    console.error("Groq llama-scout debug coach failed, trying fallback:", err);
    if (err?.status === 429) {
      await rotationService.handleRateLimit();
    }
  }

  // Fallback to standard Groq completion
  try {
    const groq = await rotationService.getClient();
    const groqMessages = [
      { role: "system", content: systemInstruction },
      ...debugMessages.map((m: any) => ({
        role: m.role === "model" ? "assistant" : "user",
        content: m.content || ""
      }))
    ];
    const completion = await groq.chat.completions.create({
      model: "llama-3.3-70b-versatile",
      messages: groqMessages as any,
      temperature: 0.5
    });
    return completion.choices[0]?.message?.content?.trim() || "";
  } catch (err) {
    console.error("Groq fallback debug coach failed:", err);
    return "Failed to get debugging advice. Check pins and try again.";
  }
};

// ??$$$
export const callGeminiRegenerateMilestoneCode = async (
  milestone: any,
  project: any
): Promise<string> => {
  const userPrompt = `Project Brief:
Objective: ${project.ideation?.objective}
Compute Brain: ${project.ideation?.compute}
BOM: ${JSON.stringify(project.bom)}

Milestone Title: ${milestone.title}
Milestone Objective: ${milestone.objective}
Milestone Components Involved: ${JSON.stringify(milestone.componentsInvolved)}
Wiring Instructions: ${milestone.wiringInstructions}

Regenerate code for this milestone.`;

  try {
    const raw = await callAI(MILESTONE_REGENERATE_PROMPT, userPrompt);
    return raw.replace(/```cpp|```python|```/g, "").trim();
  } catch (err) {
    console.error("Regenerate code failed:", err);
    return milestone.code;
  }
};

// ??$$$
export const callGeminiComponentIssue = async (
  milestone: any,
  componentKey: string,
  problem: string
): Promise<{ recommendSwap: boolean; alternativeComponent: string; explanation: string }> => {
  const userPrompt = `Milestone: ${milestone.title} (${milestone.objective})
Component in question: ${componentKey}
User reported problem: ${problem}`;

  try {
    const raw = await callAI(COMPONENT_ISSUE_SYSTEM_PROMPT, userPrompt);
    const clean = raw.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch (err) {
    console.error("Component issue analysis failed:", err);
    return { recommendSwap: false, alternativeComponent: "", explanation: "Error checking component issue." };
  }
};

// ??$$$
export const callGeminiValidateSerial = async (
  milestone: any,
  actualOutput: string
): Promise<{ pass: boolean; confidence: string; analysis: string; suggestion: string | null }> => {
  const userPrompt = `Milestone Title: ${milestone.title}
Expected Output Pattern: ${milestone.test?.expectedSerialOutput}
Pass Condition: ${milestone.test?.passCondition}

Actual Serial Output observed:
${actualOutput}`;

  try {
    const raw = await callAI(SERIAL_VALIDATION_SYSTEM_PROMPT, userPrompt);
    const clean = raw.replace(/```json|```/g, "").trim();
    return JSON.parse(clean);
  } catch (err) {
    console.error("Serial validation failed:", err);
    return { pass: false, confidence: "low", analysis: "Error running automated serial validation.", suggestion: "Please review manually." };
  }
};
