// ??$$$ group 6 - Physical Enclosure & 3D Modeling (Phase 5)
// @ts-nocheck
// ??$$$ FORGE: componentDimensions.js — Physical dimension DB for 50 common components
// Fields: width_mm, height_mm, depth_mm, mountingHoles, requiresExposure, exposureSide,
//         heatGeneration, ports (for enclosure hole generation), clearance_mm

const COMPONENT_DIMENSIONS = {
  // ─── Controllers ──────────────────────────────────────────────────────────
  ESP32_DEVKIT_V1: {
    width_mm: 52, height_mm: 28, depth_mm: 12,
    clearance_mm: 5,
    mountingHoles: true,
    requiresExposure: false,
    ports: ['usb-micro'],
    heatGeneration: 'low',
    category: 'controller',
  },
  ARDUINO_UNO: {
    width_mm: 69, height_mm: 53, depth_mm: 15,
    clearance_mm: 5,
    mountingHoles: true,
    requiresExposure: false,
    ports: ['usb-b'],
    heatGeneration: 'low',
    category: 'controller',
  },
  ARDUINO_MEGA: {
    width_mm: 102, height_mm: 53, depth_mm: 15,
    clearance_mm: 5,
    mountingHoles: true,
    requiresExposure: false,
    ports: ['usb-b'],
    heatGeneration: 'low',
    category: 'controller',
  },
  ARDUINO_NANO: {
    width_mm: 45, height_mm: 18, depth_mm: 12,
    clearance_mm: 3,
    mountingHoles: false,
    requiresExposure: false,
    ports: ['usb-mini'],
    heatGeneration: 'low',
    category: 'controller',
  },
  NODEMCU_ESP8266: {
    width_mm: 49, height_mm: 26, depth_mm: 12,
    clearance_mm: 3,
    mountingHoles: false,
    requiresExposure: false,
    ports: ['usb-micro'],
    heatGeneration: 'low',
    category: 'controller',
  },
  RASPBERRY_PI_PICO: {
    width_mm: 51, height_mm: 21, depth_mm: 4,
    clearance_mm: 3,
    mountingHoles: true,
    requiresExposure: false,
    ports: ['usb-micro'],
    heatGeneration: 'low',
    category: 'controller',
  },

  // ─── Sensors ──────────────────────────────────────────────────────────────
  PIR_HC_SR501: {
    width_mm: 33, height_mm: 25, depth_mm: 20,
    clearance_mm: 10,
    mountingHoles: true,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  ULTRASONIC_HC_SR04: {
    width_mm: 45, height_mm: 20, depth_mm: 15,
    clearance_mm: 10,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'front',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  DHT11: {
    width_mm: 16, height_mm: 12, depth_mm: 6,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  DHT22: {
    width_mm: 20, height_mm: 15, depth_mm: 8,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  BMP280: {
    width_mm: 12, height_mm: 12, depth_mm: 3,
    clearance_mm: 3,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  MPU6050: {
    width_mm: 21, height_mm: 16, depth_mm: 3,
    clearance_mm: 3,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  LDR_5MM: {
    width_mm: 8, height_mm: 8, depth_mm: 5,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  MQ2_GAS_SENSOR: {
    width_mm: 34, height_mm: 34, depth_mm: 22,
    clearance_mm: 10,
    mountingHoles: true,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'low',
    category: 'sensor',
  },
  RAIN_SENSOR: {
    width_mm: 62, height_mm: 35, depth_mm: 5,
    clearance_mm: 10,
    mountingHoles: true,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },
  SOIL_MOISTURE_SENSOR: {
    width_mm: 60, height_mm: 20, depth_mm: 5,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'front',
    ports: [],
    heatGeneration: 'none',
    category: 'sensor',
  },

  // ─── Actuators / Outputs ──────────────────────────────────────────────────
  RELAY_5V_SINGLE: {
    width_mm: 52, height_mm: 28, depth_mm: 19,
    clearance_mm: 8,
    mountingHoles: true,
    requiresExposure: false,
    ports: ['screw-terminal'],
    heatGeneration: 'medium',
    category: 'actuator',
  },
  RELAY_5V_DUAL: {
    width_mm: 75, height_mm: 55, depth_mm: 19,
    clearance_mm: 8,
    mountingHoles: true,
    requiresExposure: false,
    ports: ['screw-terminal'],
    heatGeneration: 'medium',
    category: 'actuator',
  },
  SERVO_SG90: {
    width_mm: 32, height_mm: 30, depth_mm: 12,
    clearance_mm: 10,
    mountingHoles: true,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'low',
    category: 'actuator',
  },
  SERVO_MG996R: {
    width_mm: 41, height_mm: 38, depth_mm: 20,
    clearance_mm: 12,
    mountingHoles: true,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'medium',
    category: 'actuator',
  },
  L298N_MOTOR_DRIVER: {
    width_mm: 43, height_mm: 43, depth_mm: 27,
    clearance_mm: 10,
    mountingHoles: true,
    requiresExposure: false,
    ports: ['screw-terminal'],
    heatGeneration: 'high',
    category: 'actuator',
  },
  MOSFET_IRFZ44N: {
    width_mm: 9, height_mm: 16, depth_mm: 4,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'medium',
    category: 'actuator',
  },
  STEPPER_MOTOR_NEMA17: {
    width_mm: 42, height_mm: 42, depth_mm: 40,
    clearance_mm: 8,
    mountingHoles: true,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'medium',
    category: 'actuator',
  },
  A4988_STEPPER_DRIVER: {
    width_mm: 20, height_mm: 15, depth_mm: 11,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'medium',
    category: 'actuator',
  },


  // ─── Displays ─────────────────────────────────────────────────────────────
  OLED_128X64_I2C: {
    width_mm: 28, height_mm: 27, depth_mm: 4,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'front',
    ports: [],
    heatGeneration: 'none',
    category: 'display',
  },
  LCD_16X2: {
    width_mm: 80, height_mm: 36, depth_mm: 10,
    clearance_mm: 5,
    mountingHoles: true,
    requiresExposure: true,
    exposureSide: 'front',
    ports: [],
    heatGeneration: 'none',
    category: 'display',
  },
  SEVEN_SEGMENT_4DIGIT: {
    width_mm: 42, height_mm: 24, depth_mm: 8,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'front',
    ports: [],
    heatGeneration: 'none',
    category: 'display',
  },

  // ─── Passives / Misc ──────────────────────────────────────────────────────
  LED_5MM: {
    width_mm: 6, height_mm: 6, depth_mm: 10,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'front',
    ports: [],
    heatGeneration: 'none',
    category: 'passive',
  },
  BUZZER_5V: {
    width_mm: 12, height_mm: 12, depth_mm: 9,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'passive',
  },
  PUSH_BUTTON: {
    width_mm: 12, height_mm: 12, depth_mm: 8,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'passive',
  },
  POT_10K: {
    width_mm: 16, height_mm: 16, depth_mm: 14,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'passive',
  },
  RESISTOR: {
    width_mm: 8, height_mm: 4, depth_mm: 2,
    clearance_mm: 2,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'none',
    category: 'passive',
  },
  CAPACITOR_100UF: {
    width_mm: 8, height_mm: 8, depth_mm: 12,
    clearance_mm: 3,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'none',
    category: 'passive',
  },
  BREADBOARD_HALF: {
    width_mm: 84, height_mm: 55, depth_mm: 9,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'none',
    category: 'passive',
  },

  // ─── Communication ────────────────────────────────────────────────────────
  HC05_BLUETOOTH: {
    width_mm: 38, height_mm: 16, depth_mm: 5,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'low',
    category: 'communication',
  },
  NEO6M_GPS: {
    width_mm: 36, height_mm: 35, depth_mm: 8,
    clearance_mm: 10,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'low',
    category: 'communication',
  },
  SIM800L_GSM: {
    width_mm: 24, height_mm: 22, depth_mm: 4,
    clearance_mm: 8,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'medium',
    category: 'communication',
  },
  NRF24L01: {
    width_mm: 29, height_mm: 15, depth_mm: 5,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: true,
    exposureSide: 'top',
    ports: [],
    heatGeneration: 'none',
    category: 'communication',
  },

  // ─── Power ────────────────────────────────────────────────────────────────
  LM7805_REGULATOR: {
    width_mm: 10, height_mm: 9, depth_mm: 5,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'medium',
    category: 'power',
  },
  LIPO_BATTERY_500MAH: {
    width_mm: 34, height_mm: 24, depth_mm: 6,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: false,
    ports: [],
    heatGeneration: 'none',
    category: 'power',
  },
  TP4056_CHARGER: {
    width_mm: 26, height_mm: 17, depth_mm: 4,
    clearance_mm: 5,
    mountingHoles: false,
    requiresExposure: false,
    ports: ['usb-micro'],
    heatGeneration: 'low',
    category: 'power',
  },
};

// Default fallback for unknown components
const DEFAULT_DIMENSION = {
  width_mm: 20, height_mm: 20, depth_mm: 10,
  clearance_mm: 5,
  mountingHoles: false,
  requiresExposure: false,
  exposureSide: null,
  ports: [],
  heatGeneration: 'none',
  category: 'unknown',
};

/**
 * getDimensions(key) — returns dimensions for a component key, or defaults
 */
export const getDimensions = (key) => {
  return COMPONENT_DIMENSIONS[key] || DEFAULT_DIMENSION;
};

/**
 * getAllKeys() — returns all known component keys
 */
export const getAllKeys = () => Object.keys(COMPONENT_DIMENSIONS);

export { COMPONENT_DIMENSIONS, DEFAULT_DIMENSION };
export default { getDimensions, getAllKeys, COMPONENT_DIMENSIONS };
