export const COMPONENT_FAMILIES = [
  'CONTROLLER',
  'SERVO',
  'STEPPER',
  'DC_MOTOR',
  'RELAY',
  'BUZZER',
  'LED',
  'RGB_LED',
  'LCD',
  'OLED',
  'SEVEN_SEGMENT',
  'BUTTON',
  'TOGGLE_SWITCH',
  'DIP_SWITCH',
  'ROTARY_ENCODER',
  'POTENTIOMETER',
  'JOYSTICK',
  'KEYPAD',
  'ULTRASONIC',
  'IR_RECEIVER',
  'IR_TRANSMITTER',
  'DHT11',
  'DHT22',
  'BME280',
  'BMP280',
  'MQ_SENSOR',
  'PIR_SENSOR',
  'LDR',
  'RTC',
  'EEPROM',
  'SD_CARD',
  'RFID',
  'NFC',
  'GPS',
  'BLUETOOTH',
  'WIFI_MODULE',
  'LORA',
  'NRF24',
  'CAN_MODULE',
  'RS485',
  'I2C_EXPANDER',
  'SHIFT_REGISTER',
  'MOTOR_DRIVER',
  'STEPPER_DRIVER',
  'MOSFET',
  'TRANSISTOR',
  'OPAMP',
  'ADC',
  'DAC',
  'POWER_REGULATOR',
  'BATTERY',
]

export const FAMILY_TO_CATEGORY = {
  CONTROLLER: 'Controllers',
  SERVO: 'Motors & Actuators',
  STEPPER: 'Motors & Actuators',
  DC_MOTOR: 'Motors & Actuators',
  RELAY: 'Switching',
  BUZZER: 'Outputs',
  LED: 'Outputs',
  RGB_LED: 'Outputs',
  LCD: 'Displays',
  OLED: 'Displays',
  SEVEN_SEGMENT: 'Displays',
  BUTTON: 'Inputs',
  TOGGLE_SWITCH: 'Inputs',
  DIP_SWITCH: 'Inputs',
  ROTARY_ENCODER: 'Inputs',
  POTENTIOMETER: 'Inputs',
  JOYSTICK: 'Inputs',
  KEYPAD: 'Inputs',
  ULTRASONIC: 'Sensors',
  IR_RECEIVER: 'Sensors',
  IR_TRANSMITTER: 'Outputs',
  DHT11: 'Sensors',
  DHT22: 'Sensors',
  BME280: 'Sensors',
  BMP280: 'Sensors',
  MQ_SENSOR: 'Sensors',
  PIR_SENSOR: 'Sensors',
  LDR: 'Sensors',
  RTC: 'Memory & Time',
  EEPROM: 'Memory & Time',
  SD_CARD: 'Memory & Time',
  RFID: 'Connectivity',
  NFC: 'Connectivity',
  GPS: 'Connectivity',
  BLUETOOTH: 'Connectivity',
  WIFI_MODULE: 'Connectivity',
  LORA: 'Connectivity',
  NRF24: 'Connectivity',
  CAN_MODULE: 'Connectivity',
  RS485: 'Connectivity',
  I2C_EXPANDER: 'Interfaces',
  SHIFT_REGISTER: 'Interfaces',
  MOTOR_DRIVER: 'Drivers',
  STEPPER_DRIVER: 'Drivers',
  MOSFET: 'Discrete',
  TRANSISTOR: 'Discrete',
  OPAMP: 'Analog',
  ADC: 'Analog',
  DAC: 'Analog',
  POWER_REGULATOR: 'Power',
  BATTERY: 'Power',
}

